
name: Update Copyright Year

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 1 *' # Runs at 00:00 on January 1st every year

jobs:
  update-year:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update copyright year
        run: |
          # This command finds and replaces "© 20xx" with the current year
          sed -i "s/© [0-9]\{4\}/© $(date +'%Y')/g" src/components/ContactSection.tsx

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add src/components/ContactSection.tsx
          # Commit and push only if there are changes
          git diff --staged --quiet || (git commit -m "docs: update copyright year to $(date +'%Y')" && git push)
